# Description:
#
# This function caluclates 4 different values of the parameter "beta" for no selection, weak selection,
# medium selection and stong selection following the "Stress Model". 
#
# Usage:
#
# CalculateBetas(chain.p.ref, fmax, R0, heme = TRUE/FALSE, data.dir, out.dir,
# betas.fname.id, tolerance)
#
#  Args:
#    - chain.p.ref: The chain of p.ref in the pdb file obtained from Homstrad.
#    - fmax: The maximun value for the forces that model the mutations.
#    - R0: The cut-off for the ANM ("Anisotropic Network Model") that represents the proteins.
#    - heme: argument for "globins". It can be "TRUE" or "FALSE". If it is "TRUE", the program considers the heme group.
#    - data.dir: Directory of the data. It must contain the pdb file obtained from Homstrad ("data.dir/family_coordinates.csv").
#    - out.dir: Output directory. It must contain the output generated by the function AnalyzeFamily().
#    - betas.fname.id: ID for output filenames.
#    - tolerance: 0 tolerance.
#
#  Required libraries:
#    {Bio3d}
#
#  Required functions:
#    ReadCA()
#    ReadHeme()
#    CalculateENMK()
#    CalculateKij()

CalculateBetas <- function(chain.p.ref,
                           fmax, 
                           R0,
                           heme,
                           data.dir,
                           out.dir,
                           betas.fname.id,
                           tolerance) {
  
  print("calculating betas...")
  
  # input
  n.mut.b = 200
  
  # Filenames
  pdb.fname <- file.path(data.dir, paste(p.ref, ".pdb", sep = "")) 
  
  # Read PDB of p.ref
  pdb = ReadCA(pdb.fname, chain.p.ref)
  r.p.ref = pdb$xyz.calpha
  n.aa = pdb$n.sites
  
  # Get heme coordinates, add them to CA´s coordinates and calculate the new number of sites
  if (heme == "TRUE") {
    r.heme = ReadHeme(pdb.fname, chain.p.ref)
    r.p.ref = cbind(r.p.ref, r.heme)
    n.sites = ncol(r.p.ref)
  } else {
    n.sites = n.aa
  }
  
  ### CALCULATE ENM OF THE REFERENCE PROTEIN ###
  
  # Calculate ENM of p.ref
  ENMK.p.ref = CalculateENMK(r.p.ref, CalculateKij, R0, tolerance) 
  
  ### CALCULATE PARAMETERS FOR THE SELECTION OF MUTANTS FOLLOWING THE "STRESS MODEL" ###
  
  # Set possible betas
  betas = seq(0, 10, by = 0.1)
  
  # Set possible sites to mutate
  sites.to.mutate = seq(1:ncol(r.p.ref)) # CA´s coordinates

  # Create a matrix to save p.accept
  p.accept = matrix(nrow = n.mut.b, ncol = length(betas))
  
  # Start a loop for each b
  for (b in betas) {
    print(b)
    
    # Start a loop for each mutant
    for (i in (1:n.mut.b)) {
      
      # Select mut.index
      mut.index = sample(sites.to.mutate, 1)
    
      # Calculate forces
      force = CalculateForce(mut.index, r.p.ref, ENMK.p.ref$kij, fmax) 
      f = force$f
      sum.fij.square = force$sum.fij.square
  
      # Calculate the acceptance probability of the mutation
      p.accept.mut = exp (- b * sum.fij.square)
      p.accept[i, which(betas == b)] = p.accept.mut
    }
  }

  # plot the results
  plot(betas, colMeans(p.accept), ylim = c(0, 1), main = "calcule of betas", xlab = "beta", ylab = "<p.accept>")
  abline(1, 0, col = "red")
  abline(0.8, 0, col = "orange")
  abline(0.5, 0, col = "yellow")
  abline(0.1, 0, col = "green")

  # get betas for different selection regimens
  beta.1 = betas[which(abs(colMeans(p.accept) - 1) == min(abs(colMeans(p.accept) - 1)))]
  beta.0.8 = betas[which(abs(colMeans(p.accept) - 0.8) == min(abs(colMeans(p.accept) - 0.8)))]
  beta.0.5 = betas[which(abs(colMeans(p.accept) - 0.5) == min(abs(colMeans(p.accept) - 0.5)))]
  beta.0.1 = betas[which(abs(colMeans(p.accept) - 0.1) == min(abs(colMeans(p.accept) - 0.1)))]

  # Build a list with betas
  all.betas = list("strong.sel" = beta.0.1, "medium.sel" = beta.0.5, "weak.sel" = beta.0.8, "no.sel" = beta.1) 
  
  # Create a file to save the data
  write.csv(all.betas, file = file.path(out.dir, paste(betas.fname.id, "_out_all.betas.csv", sep = "")), row.names = FALSE)
  
  print("betas calculated and saved")
}
  