
```{r setup, include = FALSE}
# set chunk options
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Introduction
In this report we compare experimental and theoretical SDi profiles and SDi profiles with MSFi. We show the figures of all families.

```{r load-packages}
# load packages
library(png)
```

```{r read-input}
# read input
input.fname <- "input_MainReport.csv"
input <- read.csv(input.fname)
```
## SDi 
```{r plot-sqrt-SDi, fig.height=4}
# satart a loop for each family
for (f in (1:nrow(input))) { 
  family <- as.character(input$family)[f]
  enm <- as.character(input$enm)[f]
  R0 = input$R0.CA[f]
  
  images.file =  paste("FIGURES_REPORTS", "/report_structure_CA_", family, "_", enm, "_R0_", R0, "_files/figure-html/", sep = '')

  img.sqrt.sdi = readPNG(paste(images.file, "comparisons-between-sqrt-profiles-1.png", sep = ""))
  #png("IMG.png")
  # par( mfrow = c( 1, 1 ) )

  #par(mar=c(0,0,0,0), xpd=NA, mgp=c(0,0,0), oma=c(0,0,0,0), ann=F)
  plot.new()
  plot.window(0:1, 0:1)

  #fill plot with image
  usr<-par("usr")    
  rasterImage(img.sqrt.sdi, usr[1], usr[3], usr[2], usr[4])
  
  text(.5,1, family, cex=1, col=rgb(.2,.2,.2,.7))
}
```

## SDi vs MSF 


```{r plot-sqrt-SDi-MSF, fig.height=4}
# satart a loop for each family
for (f in (1:nrow(input))) { 
  family <- as.character(input$family)[f]
  enm <- as.character(input$enm)[f]
  R0 = input$R0.CA[f]
  
  images.file =  paste("FIGURES_REPORTS", "/report_structure_CA_", family, "_", enm, "_R0_", R0, "_files/figure-html/", sep = '')

  img.sqrt.sdi.MSF = readPNG(paste(images.file, "sqrt-structure-MSF-comparison-1.png", sep = ""))
  #png("IMG.png")
  # par( mfrow = c( 1, 1 ) )

  #par(mar=c(0,0,0,0), xpd=NA, mgp=c(0,0,0), oma=c(0,0,0,0), ann=F)
  plot.new()
  plot.window(0:1, 0:1)

  #fill plot with image
  usr<-par("usr")    
  rasterImage(img.sqrt.sdi.MSF, usr[1], usr[3], usr[2], usr[4])
  text(.5,1, family, cex=1, col=rgb(.2,.2,.2,.7))
 }
```